### ISSUE TITLE
Cannot instantiate actor from imported module

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#668] opened 2022-06-09 22:39 UTC
It is not possible to instantiate actors from imported modules!

```
kll@Boxy:~/terastream/acton/compiler/test/actonc/regressions/import_actor$ ~/terastream/acton/dist/bin/actonc build
Compiling foo.act for release

******************** Compilation error
Module foo does not export 'Bar$newact'
kll@Boxy:~/terastream/acton/compiler/test/actonc/regressions/import_actor$ 
```

I committed this regression in #666, so simply try to build that for a reproduction

**Comment by plajjan** [comment] 2022-06-22 10:23
@nordlander is this similar to the not-possible-to-instantiate classes or different?

This one is not as critical for me, but if it's of similar character and easily fixed...!?

**Comment by nordlander** [comment] 2022-06-22 10:50
Hmm, where has the example gone? There's no `test/actonc/regressions/` directory anymore...

**Comment by plajjan** [comment] 2022-06-22 11:23
test/regression_auto/import... I think

**Comment by nordlander** [comment] 2022-06-22 14:57
Problem fixed by PR #731. The test case still fails, though, seemingly because of a bad root argument in the test config. Leaving the issue open for that reason (for @plajjan  to fix!).

**Comment by plajjan** [comment] 2022-06-23 08:12
Test case now working after #737 fixes.

**Closed** 2022-06-23 18:47 UTC
Labels: bug, Compiler
