### ISSUE TITLE
Non-exhaustive patterns error when compiling acton-streamer

### ISSUE THREAD

**Issue by ciaran2** [actonlang/acton#1558] opened 2023-10-13 16:09 UTC
### Acton Version

0.17.0.20231012.10.19.40

### Reproduction code

Seems to be triggered by the lines in this diff: https://github.com/dt-terastream/acton-streamer/commit/7cd7c3a273e862015f0f367454eac60da17f605c

### Error output

```
actonc build
Building project in /home/ccain/acton-streamer
  Compiling tsdb/json-err.act for release
   Already up to date, in    0.000 s
  Compiling tsdb/http.act for release
   Already up to date, in    0.002 s
  Compiling tsdb/m3.act for release
   Already up to date, in    0.000 s
  Compiling tsdb/test.act for release
   Already up to date, in    0.000 s
  Compiling acton_streamer/common/utils.act for release
   Already up to date, in    0.003 s
  Compiling acton_streamer/common/mod.act for release
   Already up to date, in    0.005 s
  Compiling acton_streamer/common/io.act for release
   Already up to date, in    0.002 s
  Compiling acton_streamer/net/netconf.act for release
   Already up to date, in    0.000 s
  Compiling acton_streamer/nsoapi/proto.act for release
   Already up to date, in    0.002 s
  Compiling acton_streamer/nsoapi/conf.act for release
   Already up to date, in    0.001 s
  Compiling acton_streamer/nsoapi/channel.act for release
   Already up to date, in    0.000 s
  Compiling acton_streamer/nsoapi/cdb.act for release
   Already up to date, in    0.002 s
  Compiling acton_streamer/nsoapi/schema.act for release
   Already up to date, in    0.007 s
  Compiling acton_streamer/nsoapi/conv.act for release
   Already up to date, in    0.000 s
  Compiling acton_streamer/nso/subscriber.act for release
   Already up to date, in    0.001 s
  Compiling acton_streamer/main/config.act for release
   Already up to date, in    0.001 s
  Compiling acton_streamer/nsoapi/maapi.act for release
   Already up to date, in    0.002 s
  Compiling acton_streamer/nso/writer.act for release
   Already up to date, in    0.000 s
  Compiling acton_streamer/tsdb/writer.act for release
   Already up to date, in    0.000 s
  Compiling acton_streamer/main/main.act for release

ERROR: Error when compiling acton_streamer.main.main module: Type error
actonc: Acton/TypeM.hs:(184,39)-(186,87): Non-exhaustive patterns in case
```

**Comment by plajjan** [comment] 2023-10-14 19:37
@nordlander this is for you! :)

**Comment by sydow** [comment] 2023-10-16 10:14
@plajjan and @nordlander: Unfortunately, I think it is for me...

**Comment by sydow** [comment] 2023-10-16 10:17
I just tried to reproduce it without success. I did 

git pull
make

in the acton-streamer directory and compilation was successful!?

**Comment by plajjan** [comment] 2023-10-16 11:44
@sydow no, these changes are only on a branch right now. Do `git checkout 7cd7c3a273e862015f0f367454eac60da17f605c` and then I think you will see the failure?

**Comment by sydow** [comment] 2023-10-16 12:49
Yes, now I get the error message you reported. In fact, together with some other minor improvements I did (to fix the error message in your minimal example in #1555) I can see that the error is the incompatibility between the actor definition on line 586 (which has four arguments) and the actor creation on line 317 (which gives only 3 args).

We have a general problem as to when I should push improvements to type error messages. We know we have around 100 locations with NoInfo messages to improve. Today I also saw that the NoInfo 86 error gives no location info — and that is a shortcoming of the Parser, which has omitted location info in some cases (since we anyhow didn’t show location in type errors at that point…) So this could mean more than 100 pushes if I push after every minor improvement, and that seems unreasonable.

**Comment by plajjan** [comment] 2023-10-16 19:56
I don't understand. What is your concern with 100 pushes? In what way is it unreasonable? :)

Is it the small size of commits that bother you? That it would be better to group this up into larger commits? I don't think that's a problem at all. 100 small commits, each improving a type error is completely fine! :)

**Comment by plajjan** [comment] 2023-10-31 21:51
I don't think there is anything actionable left that is directly related to the original issue, so closing this.

**Closed by plajjan** 2023-10-31 21:51 UTC
Labels: bug, Compiler
