### ISSUE TITLE
Allow function calls to declared-only / stub functions in stub mode

### ISSUE THREAD

**Issue by plajjan** [actonlang/acton#695] opened 2022-06-14 21:26 UTC
I have this simple acton module:
```
def lookup_a(name : str):
    return _lookup_a(name)

_lookup_a : action(name : str) -> Set[str]
```

the idea is to implement `_lookup_a` in C, so it's just a type signature here. However, compilation of this module fails with:
```
kll@Boxy:~/terastream/acton/stdlib$ ../dist/bin/actonc src/net.act --stub --cgen
******************** Compilation error
 6:12-20
  |
6 |    return _lookup_a(name)
  |           ^^^^^^^^^
Name _lookup_a is reserved but not yet defined
```

I do not see a way to work around this. We've got to fix this in actonc so we can build modules like this, right?

**Comment by nordlander** [comment] 2022-06-15 08:16
This particular issue would be resolved by simply swapping the statement order so the signature comes before the `def`.

Some motivation for this "restriction":

Python doesn't distinguish between function declarations and other, potentially mutating statements; nor does it care too much about syntactic scoping rules. As a compiled language, Acton had to be given a more firm syntactic definition, especially regarding the circumstances under which a name can be referenced before it's defined.

After various experiments I came to the conclusion that a simple syntactic rule is the best: a group of adjacent function definitions can reference each other in a mutually recursive manner, and so can a group of adjacent classes/actors/protocols and extensions. But any intervening statement that's not one of these so called _declarations_ breaks the look ahead capability; in these, only references to previously defined names are possible.

Signatures don't count as declarations in this respect, mostly for pragmatic reasons (there's rarely a need to put a signature on something that's already defined) and a minor technicality (a signature is gramatically just a variant of Python's annotated variable assignmnet, but without the right-hand side).

But I agree that in the current example, where the signature is a place-holder for a concrete but externally defined function, it feels more natural to view it as part of a mutually recursive declaration group. Maybe we should consider not using signatures for that purpose? How about
```
    def lookup_a(name : str):
        return _lookup_a(name)

    def _lookup_a(name : str) -> Set[str]:
        ...
```
Just brainstorming...

**Comment by nordlander** [comment] 2022-06-16 15:25
My bad, the problem is of course that function _lookup doesn't exist as concrete code, so swapping the statement order won't help (even though my description of how signatures work is correct, so that part is actually not a bug).

But there's a new take on this topic: see PR #706. Especially file test/regressions_auto/not_implemented.act.

**Closed by nordlander** 2022-06-16 15:25 UTC
Labels: bug, Compiler
