### ISSUE TITLE
"Module math does not exist"

### ISSUE THREAD

**Issue by sydow** [actonlang/acton#674] opened 2022-06-10 12:01 UTC
The following program gives the compilation error of the title:

``` 
import numpy as np

def harmonic(n):
    return np.sum(1/np.arange(1,n+1,1),0)

actor main(env):

    def interact(input):
        n = int(input.strip("\n"))
        print(harmonic(n))
    
    env.stdin_install(interact)
```

If the definition of interact is moved to the top level, outside actor main, everything is fine; the program compiles and runs as expected.

**Comment by sydow** [comment] 2022-06-10 14:17
Well, the quotation in the title was intentional. The problem is not that module math does not exist but an error message which claims that to be the case...

**Comment by plajjan** [comment] 2022-06-10 14:54
Oh sorry, I was too quick :/

**Comment by plajjan** [comment] 2024-01-09 13:17
This no longer fails. Not sure when or where it was fixed but since we can't reproduce the error anymore I'm closing this issue.

**Closed by plajjan** 2024-01-09 13:17 UTC
Labels: bug, Compiler
