### ISSUE TITLE
Compiler performance since v0.13.1

### ISSUE THREAD

**Issue by ddjoh** [actonlang/acton#1113] opened 2022-11-17 14:23 UTC
With acton v0.13.1 and later versions, the compilation time of a program such as the one below becomes impractical. In this example the methods write_some_* seem to increase the compilation time in an exponential fashion.

```
class BufferWriter(object):
    @property
    parts: list[bytes]

    def __init__(self):
        self.parts = []

    def write_bytes(self, b: bytes):
        self.parts.append(b)

    def write_u8(self, v: int):
        # self.write_bytes(bytes([v & 0xFF])) # BUG: Runtime error on bitwise operations
        self.write_bytes(bytes([v % 0x100]))

    def write_i32_be(self, v: int):
        # self.write_bytes(bytes([v >> 24 & 0xFF, v >> 16 & 0xFF, v >> 8 & 0xFF, v & 0xFF])) # BUG: Runtime error on bitwise operations
        self.write_bytes(bytes([v // 0x1000000 % 0x100, v // 0x10000 % 0x100, v // 0x100 % 0x100, v % 0x100]))

    def write_some_1(self, x: int):
        self.write_u8(1)
        self.write_i32_be(x)

    def write_some_2(self, x: int):
        self.write_u8(2)
        self.write_i32_be(x)

    def write_some_3(self, x: int):
        self.write_u8(3)
        self.write_i32_be(x)

    def write_some_4(self, x: int):
        self.write_u8(4)
        self.write_i32_be(x)

    def write_some_5(self, x: int):
        self.write_u8(5)
        self.write_i32_be(x)

    def write_some_6(self, x: int):
        self.write_u8(6)
        self.write_i32_be(x)

    def write_some_7(self, x: int):
        self.write_u8(7)
        self.write_i32_be(x)

    def write_some_8(self, x: int):
        self.write_u8(8)
        self.write_i32_be(x)

    def write_some_9(self, x: int):
        self.write_u8(9)
        self.write_i32_be(x)
```

**Comment by plajjan** [comment] 2022-11-17 15:06
@ddjoh so performance is better in v0.13.0 or which was the earlier known good version?

**Comment by plajjan** [comment] 2022-11-21 15:58
@nordlander I think this issue should be top priority! :)

**Comment by nordlander** [comment] 2022-11-22 17:19
Curious error, but I've found there's a quick workaround: delete the property signature for "parts"! It's inferred from the shape of the __init__ body anyway.

And the underlying problem is related to the syntax of classes, which I want us to agree on before I embark on the efficiency bug hunt. It might be an artificial problem, after all...

**Comment by ddjoh** [comment] 2022-11-23 14:12
While removing the property signature does make the above sample compile in a reasonable time, it seems the general issue remains, in that a simple addition such as the `write_i16_be` below, again takes the compilation time beyond viability again.

```
class BufferWriter(object):
    #@property
    #parts: list[bytes]

    def __init__(self):
        self.parts = []

    def write_bytes(self, b: bytes):
        self.parts.append(b)

    def write_u8(self, v: int):
        # self.write_bytes(bytes([v & 0xFF])) # BUG: Runtime error on bitwise operations
        self.write_bytes(bytes([v % 0x100]))

    def write_i16_be(self, v: int):
        # self.write_bytes(bytes(v >> 8 & 0xFF, v & 0xFF])) # BUG: Runtime error on bitwise operations
        self.write_bytes(bytes([v // 0x100 % 0x100, v % 0x100]))

    def write_i32_be(self, v: int):
        # self.write_bytes(bytes([v >> 24 & 0xFF, v >> 16 & 0xFF, v >> 8 & 0xFF, v & 0xFF])) # BUG: Runtime error on bitwise operations
        self.write_bytes(bytes([v // 0x1000000 % 0x100, v // 0x10000 % 0x100, v // 0x100 % 0x100, v % 0x100]))

    def write_some_1(self, x: int):
        self.write_u8(1)
        self.write_i32_be(x)

    def write_some_2(self, x: int):
        self.write_u8(2)
        self.write_i32_be(x)

    def write_some_3(self, x: int):
        self.write_u8(3)
        self.write_i32_be(x)

    def write_some_4(self, x: int):
        self.write_u8(4)
        self.write_i32_be(x)

    def write_some_5(self, x: int):
        self.write_u8(5)
        self.write_i32_be(x)

    def write_some_6(self, x: int):
        self.write_u8(6)
        self.write_i32_be(x)

    def write_some_7(self, x: int):
        self.write_u8(7)
        self.write_i32_be(x)

    def write_some_8(self, x: int):
        self.write_u8(8)
        self.write_i32_be(x)

    def write_some_9(self, x: int):
        self.write_u8(9)
        self.write_i32_be(x)
```

**Comment by nordlander** [comment] 2022-11-23 14:38
Ok, I need to get to the bottom of this behavior anyway! Starting digging...

**Comment by plajjan** [comment] 2022-11-24 12:23
@ddjoh side note (from @sydow), related to your commented out code. Bitwise operations are not supported for the int type. Try using a `i64` instead. I think in this code, it would be fine using fixed size ints, right?

**Comment by ddjoh** [comment] 2022-11-24 12:58
We'd mostly be fine except for u64 types. Also without a way to convert from int to i64 I think we might end up having to enforce i64 instead of int in any dependent code.

**Comment by sydow** [comment] 2022-11-24 16:35
One can convert an int to an i64 using the i64 constructor: a = i64(e) converts an expression e of type int to i64. The conversion checks the value; if it is too large for i64 an exception is raised.  

This didn’t work until a couple of minutes ago; when I intended to write this mail I checked it and there was a syntactic mistake in __builtin__.act... So you need to pull the code from git. 

Regarding u64, it is true that you can’t be sure to get an unsigned 64 bit value by converting to i64. For the moment, you will have to rely on using the mod operator and checking for non-negativeness.

**Comment by plajjan** [comment] 2022-11-25 08:56
I guess the problem is that we might receive an u64 from the other end we are communicating with in @ddjoh application code. The particular methods we are looking at now, like `write_i32_be`, deals with i32 etc but there are equivalent for u64, right @ddjoh? .. and for that, I guess we'd really need a `u64` type if we are going with a fixed size variable and not `int`.

**Comment by sydow** [comment] 2022-11-25 10:48
I did not plan to do anything with number types until we decide on the general picture, but if you urgently need u64, it would not take much time to offer it. Copy and paste from i64 and insert unsigned here and there…

So what do you do with these words in the application? Arithmetic, comparisons, bit operations… Or all of it?

Björn

**Comment by ddjoh** [comment] 2022-11-25 11:55
I think we'll be fine with using div/mod where we otherwise would be using shift/and, in that the performance difference is probably negligible in the context, which is en-/de-coding datastructures for communicating with another system where other costs usually dominate.

If, at some point in the future, the current workaround seems insufficient we can always revisit the other options, whether it's bit operations for variable or fixed size integers.

**Comment by plajjan** [comment] 2022-11-25 12:40
@sydow I think we're pretty certain that we want a u64 type. Isn't the lions share of the code unchanged for i64/u64 regardless of what we decide in the general picture, like that's more on a type level, no? so with that, we might as well go ahead and implement u64 now and make any necessary adjustments to int/i64/u64 later?

**Comment by plajjan** [comment] 2022-12-07 00:01
Ok, as reported by @nordlander, this issue is fixed, so closing. I hope that aligns with your observations @ddjoh, if not, then shout and we'll reopen this or perhaps open a new issue!?

**Closed by plajjan** 2022-12-07 00:01 UTC
Labels: bug, Compiler
